// <auto-generated />
using System;
using EAuditoria.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EAuditoria.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EAuditoria.Domain.Entities.Empresa", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<bool>("Ativo").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(true).HasColumnName("ativo");
                b.Property<DateTime?>("AtualizadoEm").HasColumnType("timestamp with time zone").HasColumnName("atualizado_em");
                b.Property<string>("Cnpj").IsRequired().HasMaxLength(14).HasColumnType("character varying(14)").HasColumnName("cnpj");
                b.Property<DateTime>("CriadoEm").HasColumnType("timestamp with time zone").HasColumnName("criado_em");
                b.Property<string>("RazaoSocial").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("razao_social");
                b.Property<int>("RegimeTributario").HasColumnType("integer").HasColumnName("regime_tributario");
                b.HasKey("Id");
                b.HasIndex("Cnpj").IsUnique().HasDatabaseName("ix_empresas_cnpj");
                b.ToTable("empresas");
            });

            modelBuilder.Entity("EAuditoria.Domain.Entities.EntregaObrigacao", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<DateTime>("CriadoEm").HasColumnType("timestamp with time zone").HasColumnName("criado_em");
                b.Property<DateTime>("DataEntrega").HasColumnType("timestamp with time zone").HasColumnName("data_entrega");
                b.Property<Guid>("ObrigacaoId").HasColumnType("uuid").HasColumnName("obrigacao_id");
                b.Property<string>("Observacao").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("observacao");
                b.HasKey("Id");
                b.HasIndex("ObrigacaoId").IsUnique().HasDatabaseName("ix_entregas_obrigacao_id");
                b.ToTable("entregas_obrigacoes");
            });

            modelBuilder.Entity("EAuditoria.Domain.Entities.ObrigacaoAcessoria", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<int>("AnoCompetencia").HasColumnType("integer").HasColumnName("ano_competencia");
                b.Property<int>("Competencia").HasColumnType("integer").HasColumnName("competencia");
                b.Property<DateTime>("CriadoEm").HasColumnType("timestamp with time zone").HasColumnName("criado_em");
                b.Property<Guid>("EmpresaId").HasColumnType("uuid").HasColumnName("empresa_id");
                b.Property<int>("Periodicidade").HasColumnType("integer").HasColumnName("periodicidade");
                b.Property<int>("Status").HasColumnType("integer").HasColumnName("status");
                b.Property<int>("Tipo").HasColumnType("integer").HasColumnName("tipo");
                b.Property<DateTime>("Vencimento").HasColumnType("timestamp with time zone").HasColumnName("vencimento");
                b.HasKey("Id");
                b.HasIndex("EmpresaId", "Competencia", "AnoCompetencia").HasDatabaseName("ix_obrigacoes_empresa_mes_ano");
                b.HasIndex("EmpresaId", "Tipo", "Competencia", "AnoCompetencia").IsUnique().HasDatabaseName("ix_obrigacoes_empresa_tipo_competencia");
                b.HasIndex("Vencimento", "Status").HasDatabaseName("ix_obrigacoes_vencimento_status");
                b.ToTable("obrigacoes_acessorias");
            });

            modelBuilder.Entity("EAuditoria.Domain.Entities.EntregaObrigacao", b =>
            {
                b.HasOne("EAuditoria.Domain.Entities.ObrigacaoAcessoria", "Obrigacao")
                    .WithOne("Entrega")
                    .HasForeignKey("EAuditoria.Domain.Entities.EntregaObrigacao", "ObrigacaoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Obrigacao");
            });

            modelBuilder.Entity("EAuditoria.Domain.Entities.ObrigacaoAcessoria", b =>
            {
                b.HasOne("EAuditoria.Domain.Entities.Empresa", "Empresa")
                    .WithMany("Obrigacoes")
                    .HasForeignKey("EmpresaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Empresa");
            });

            modelBuilder.Entity("EAuditoria.Domain.Entities.Empresa", b => { b.Navigation("Obrigacoes"); });
            modelBuilder.Entity("EAuditoria.Domain.Entities.ObrigacaoAcessoria", b => { b.Navigation("Entrega"); });

            modelBuilder.Entity("EAuditoria.Domain.Entities.Usuario", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                b.Property<bool>("Ativo").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(true).HasColumnName("ativo");
                b.Property<DateTime>("CriadoEm").HasColumnType("timestamp with time zone").HasColumnName("criado_em");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("email");
                b.Property<string>("Nome").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("nome");
                b.Property<string>("Perfil").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("perfil");
                b.Property<string>("SenhaHash").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("senha_hash");
                b.Property<DateTime?>("UltimoLoginEm").HasColumnType("timestamp with time zone").HasColumnName("ultimo_login_em");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique().HasDatabaseName("ix_usuarios_email");
                b.ToTable("usuarios");
            });
#pragma warning restore 612, 618
        }
    }
}
